name: CI (Build and Linting Check)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

# Yeh environment variable warning ko khatam kar dega aur Node 24 use karega
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
